spring:
  application:
    name: CRUDApp
  datasource:
    url: jdbc:postgresql://localhost:5432/crudapp
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080